### ISSUE TITLE
Familiarize with React Native

### ISSUE THREAD

**Issue by anisfeld** [umbrela-savings/app#1]
Purpose:
> To gain background knowledge on JavaScript React and React Native frameworks.

Your first task is to complete tutorials for React and React Native.
- Review javascript:
   - [x] [General js guide from mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript) (go over re-introduction, skim other material. Notice that some of the js here is not in React!)
   - [x] [javascript for react](https://www.robinwieruch.de/javascript-fundamentals-react-requirements/)
- [x] https://reactjs.org/tutorial/tutorial.html
- [x] https://facebook.github.io/react-native/docs/tutorial
    - use expo for getting started
- [x] set-up your environment for developing in React Native

Since you have used elm before, these should be somewhat familiar. Nevertheless, take the time to go through them carefully. If these tutorials are not working for you or you want more information feel free to look for it! I think there's a video where a human goes through the react-native tutorial and points out important details! Share what you find in this thread!

We've allotted 6 - 10 hours for this.

**Comment by HaroldLeo** [comment]
### The order of these tutorials is pretty good in general. 
- The [re-intro to js guide](https://developer.mozilla.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript) and [js for react guide](https://www.robinwieruch.de/javascript-fundamentals-react-requirements/) are helpful as a start. 
- The [react hands-on tutorial](https://reactjs.org/tutorial/tutorial.html) is a good way to practice and implement some of the fundamentals from the guide. 
  - Completing the extra tasks listing in the **Wrapping Up** section is also very helpful to my understanding of react in general. 
  - This [documentation](https://reactjs.org/docs/hello-world.html) is similar to the react-native one which is more conceptual and step-by-step in a sense. 
- The [react-native guide](https://facebook.github.io/react-native/docs/tutorial) is also helpful, but it does not provide a hands-on project like the react guide. If you are looking for a practice project, this [youtube video](https://youtu.be/6ZnfsJ6mM5c) is a pretty good starting point.
