### ISSUE TITLE
Native vs. React Web app

### ISSUE THREAD

**Issue by anisfeld** [umbrela-savings/app#14]
Tim suggested that it would be easier to develop an MVP as a web app rather than a phone app.  From a UX perspective we think a phone app is superior. However, if we can develop a website much faster, it could be worth starting as a website.
- Tim said we could later convert the react web app to a react native app.

Objective
> Estimate how much time both versions would take to complete an MVP.

Spend 2-4 hours researching this question. Perhaps someone already has a blog post comparing these etc. Consider how we could use templates to speed up development.
- [x] In this ticket, make a table comparing the benefits and costs of react v react native development.
- [x] Investigate templates (Tim recommended [this](themeforest.com))
  - can you find similar templates for native? 
- [x] How costly is it to convert a react web app to a native mobile app? (Ie. how much does the code base have to change?)

**Comment by HaroldLeo** [comment]
Websites that are found to be useful: 

- https://www.hswsolutions.com/services/mobile-web-development/mobile-website-vs-apps/

- https://brainhub.eu/blog/app-vs-website-which-to-develop-first/

||mobile website|mobile app|
|:-:|:-:|:-:|
| Immediacy |✔|| 
| Compatibility |✔||
| Upgradability |✔||
| Findability |✔||
| Shareability |✔||
| Reach |✔||
| Life Cycle |✔||
| Time & Cost |✔||
| Support & Maintenance |✔||
| Interactivity/Gaming ||✔|
| Regular Usage/Personalization ||✔|
| Complex Calculations/Reporting with Visualization ||✔|
| Native Functionality/Processing Required ||✔|
| Push Notifications ||✔|
| No Connection Required ||✔|
| User Loyalty ||✔|
| Performance & Speed ||✔|

**Comment by HaroldLeo** [comment]
An interesting finding is that there aren't too many themes for mobile websites built with reactjs

**Comment by HaroldLeo** [comment]
https://bit.dev/: components that other people wrote in react that can be shared

**Comment by HaroldLeo** [comment]
In general, many articles I found claim that there are a certain number of differences between react and react native. 

This [website](http://jkaufman.io/react-web-native-codesharing/) claims that it only requires changing the rendering such as from `<div>` to `<View>` and from `<span>` to `<Text>`. 

In addition, another [website](https://medium.com/appnroll-publication/switch-between-react-and-react-native-548267e1348a) suggests that there will be different packages used such as **react-router** to **react-navigator** and components such as **localStorage** to **asyncStorage**. The code for styles will also be different. Moreover, some platform-specific code would not look that good. Testing the app might also take longer than the web app. 

This [website](https://hackernoon.com/code-reuse-using-higher-order-hoc-and-stateless-functional-components-in-react-and-react-native-6eeb503c665) introduces the idea of Higher Order Components and Stateless Functional Component to allow more code being reusable between react and react native. 

There are also [packages](https://github.com/necolas/react-native-web) that allow react native apps for web. 

Another approach would be developing both mobile web-app and moble apps at the same time:
There are many tutorials on this such as [website1](https://codeburst.io/reusing-code-between-react-js-and-react-native-effectively-12bb4fbf7a70), [website2](https://blog.bitsrc.io/how-to-react-native-web-app-a-happy-struggle-aea7906f4903), [website3](https://dev.to/kylessg/a-sensible-approach-to-cross-platform-development-with-react-and-react-native-57pk). 

As a result, it does not seem that converting a react web app to a native mobile app would not be a disaster in terms of changing the code. @anisfeld @sstaple15

**Comment by anisfeld** [comment]
Thanks for your work on this @Hongji! 

We met in person and conclude that Mobile v Web development is a trade-off of user experience vs ease of development. We felt the user experience benefits of a mobile app including ease of authentication and push notifications make it worth the higher development costs. We'll see!!

I'm closing #14 and moving the remaining checkbox to a new ticket.
