### ISSUE TITLE
UC01a-F: User wants to create a new account 

### ISSUE THREAD

**Issue by anisfeld** [umbrela-savings/app#15]
> The first user hears about our app and wants to create an account.

- [x] sign up button (first page)
- [x] new account form
  - [x] username
  - [x] name
  - [x] email or phone number
  - [ ] (option to add payment methods??)
- [x] submit button (brings to user page)

- Question: Do we want more information in the initial screening? (We will capture some information during circle formation or circle joining).

**Comment by anisfeld** [comment]
We discussed in real life and have two new goals for @HaroldLeo 
- [x] connect to backend API
- [ ] figure out if there is a more elegant way to capture fields from the front end. 
   - [ ] more specifically is there a near automatic way to CRUD out new models? (Researching this can make our lives much easier and is worth a good dive into resources!)
   - [ ] can we design the app so that adding or changing the model fields requires minimal changes to code. (This is not a huge deal if not, but we just need to be more mindful in the beginning of a sprint about field names).

**Comment by HaroldLeo** [comment]
Maybe future (backend?) improvements: 
- Checking if the email already exists or not (probably in the backend code?)
- Right now the code logs a user in immediately after the user is registered. The backend code seems to allow this action as well. Will see if this should be changed or not.
