### ISSUE TITLE
Test App feature: create user

### ISSUE THREAD

**Issue by anisfeld** [umbrela-savings/app#2]
The "Test App" will be our first attempt at the developing process! We are writing a test app that is a messenger app (hopefully we can pull some of the code from this into Umbrela!). 

I have ticketed the app step by step as I see fit, but I'm likely missing something important, so I highly value your ability to communicate gaps and help update tickets!!

For now you will design the app against a fake backend. Depending on timing, we may go through a second round where we flesh out the development against a Django API and add richness to the app. 

Our goal here is to gain comfort with react native in a low-stakes environment and figure out our preferred git usage. After talking with Michael, I think we'll try using forks of the `umbrela-savings` master. I think you'll still use branches to make clean changes to your master, but will only have code review when pulling the fork back into `umbrela-savings` master.  (Michael will give a short class on using github for software engineering)

- [x] Create a homepage that has a "log-in" and "sign-up" button. 
- [x] Click on "sign-up" button and land on sign-up page
- [x] Collect `username`, `name` and `password` 
    - ok to be in plain text for now
    - write to a file for now

**Comment by HaroldLeo** [comment]
Collecting the info of a user will be stored in `db.json` file with the help of [json-server](https://github.com/typicode/json-server), which is also helpful for #3 log-in

**Comment by HaroldLeo** [comment]
Was able to get the local json-server working with `Fetch` api with `POST` requests

**Comment by HaroldLeo** [comment]
further improvement can include
- adding email (if it is necessary)
- adding a second text field for users to double check their password
- checking for the format of the input with restrictions (e.g. email format must be right)

**Comment by anisfeld** [comment]
Hi @HaroldLeo: 

Two process things.

- As you work on an issue push code to github and put the issue number in the commit message (e.g. `git commit -m '#2 fetch works'`)  
- You should request code review using a pull request and then pull code into `master` (or which ever branch we're working against). I should be able to run the code you have written at the very least. Hopefully at this stage some of our supporting advisors can review code and give feedback on style etc. as well.

Let me know what you think!
