### ISSUE TITLE
Test App feature: log-in page

### ISSUE THREAD

**Issue by anisfeld** [umbrela-savings/app#3]
After signing up, the user will sign in to access the app.

- [x] On home page, when person clicks log-in make a pop-up that asks user to authenticate. 
- [x] Write code to check authentication against a your `json` sign-up file

**Comment by HaroldLeo** [comment]
Finished with the json-server and a local json file, so for authentification, the method here is retrieving an entire list of users from `db.json` and compare the username and password. 

I also used the [Authentication flows](https://reactnavigation.org/docs/en/auth-flow.html) from react navigation for switching between screens. 

Right now the organization of files is messy, so I will organize them in the future
